title: PythonLove
author: CalmXin
description: Welcome to PythonLove — where code meets passion.
baseurl: ""
url: "https://scripts.pythonlove.com"
theme: Hacker
plugins:
  - jekyll-feed
  - jekyll-sitemap