title: Python Love
author: CalmXin
description: Welcome to PythonLove — where code meets passion.
baseurl: ""
url: "https://script.pyth.onl"
include:
    - favicon.ico
theme: jekyll-theme-hacker
plugins:
    - jekyll-feed
    - jekyll-sitemap